/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * kayasUI.java
 *
 * Created on Feb 24, 2012, 9:13:09 PM
 */
package kaya.kayasUIpaket;

import java.awt.Component;
import java.awt.Rectangle;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.UnsupportedLookAndFeelException;
import kaya.kayaClassPaket.*;
//import java.io.BufferedReader;
//import java.io.IOException;
//import java.io.InputStreamReader;
import java.io.*;   /////////
import java.net.*;///////
import java.nio.file.FileVisitOption;
import java.nio.file.Files;
import java.util.EnumSet;
import java.util.Enumeration;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.mail.internet.AddressException;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileSystemView;
import javax.swing.text.BadLocationException;
import javax.swing.text.DefaultCaret;
import kaya.kayasServerUIpaket.kayasClientSocket;
import kaya.kayasServerUIpaket.kayasServerSocketUI;

/**
 *
 * @author kaya
 */
public class kayasUI extends javax.swing.JFrame {

    // global degiskenler
    LinkedList<NetworkInterface> networkArayuzList;
    LinkedList<LinkedList<String>> networkArayuzInfos;
    LinkedList<LinkedList<String>> systemPropertiesInfos;
    LinkedList<LinkedList<String>> runtimeInfos;
    LinkedList<LinkedList<String>> urlInfos;
    LinkedList<LinkedList<String>> urlConnectionInfos;
    LinkedList<LinkedList<String>> HttpUrlConnectionInfos;
    LinkedList<URL> visitedURLs=new LinkedList<URL>();

    /**
     * Creates new form kayasUI
     */
    public kayasUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame_systemProperties = new javax.swing.JFrame();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea_descriptionSystem_Runtime = new javax.swing.JTextArea();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTable_systemProperties = new javax.swing.JTable();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTable_runtime = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton_Git = new javax.swing.JButton();
        jTextField_URL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea_Mesaj = new javax.swing.JTextArea();
        jScrollPane15 = new javax.swing.JScrollPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_Command = new javax.swing.JTextField();
        jButton_Execute = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane_ShellVerbose = new javax.swing.JScrollPane();
        jTextArea_ShellVerbose = new javax.swing.JTextArea();
        jLabel_shellVerbose_executing = new javax.swing.JLabel();
        jScrollPane_shellCommandHistory = new javax.swing.JScrollPane();
        jList_shellCommandHistory = new javax.swing.JList();
        jLabel22 = new javax.swing.JLabel();
        jButton_clearVerbose = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_URL = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_HTMLKaynak = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jEditorPane_url = new javax.swing.JEditorPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_setFrom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_setRecipient = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_setSubject = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_setText = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox_smtpHost = new javax.swing.JComboBox();
        jSpinner_smtpPort = new javax.swing.JSpinner();
        jComboBox_smtpAuth = new javax.swing.JComboBox();
        jComboBox_smtpStartTLS = new javax.swing.JComboBox();
        jButton_sendEPosta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea_epostaVerbose = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList_networkArayuzler = new javax.swing.JList();
        jButton_getNetworkInterfaces = new javax.swing.JButton();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTable_networkArayuz = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea_descriptionNetworkArayuz = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        jButton_system_runtime_PropertiesGetir = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTable_URL2 = new javax.swing.JTable();
        jScrollPane22 = new javax.swing.JScrollPane();
        jTable_URLConnection = new javax.swing.JTable();
        jScrollPane23 = new javax.swing.JScrollPane();
        jTable_HttpURLConnection = new javax.swing.JTable();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea_descriptionURL_HTTP_Connection = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jComboBox_urlHistory = new javax.swing.JComboBox();
        jButton_back = new javax.swing.JButton();
        jButton_setLookAndFeel = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton_initializeAndSetVisible = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();

        jLabel19.setText("Açıklama (Description)");

        jTextArea_descriptionSystem_Runtime.setColumns(20);
        jTextArea_descriptionSystem_Runtime.setEditable(false);
        jTextArea_descriptionSystem_Runtime.setLineWrap(true);
        jTextArea_descriptionSystem_Runtime.setRows(5);
        jScrollPane12.setViewportView(jTextArea_descriptionSystem_Runtime);

        jTable_systemProperties.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        /////////// Bu kodu internetten buldum.
        // "jTable" ın "currentItemChanged" gibi bir olayı yokmuş.
        // Kendimizin yazması gerekiyor.

        //    ListSelectionModel rowSM2 = jTable_serverSocket.getSelectionModel();
        //rowSM2.addListSelectionListener(new ListSelectionListener() {
            //public void valueChanged(ListSelectionEvent e) {
                //ListSelectionModel rowSM2 = (ListSelectionModel)e.getSource();
                //int selectedIndex = rowSM.getMinSelectionIndex();
                // do something with selected index
                //kayaNetworkAbstractClass1.tableInfo2TextArea(mySunucuSoketInfos, jTable_serverSocket, jTextArea_descriptionServerSocket);
                //kayaNetworkAbstractClass1.tableInfo2TextArea(mySunucuSoketInfos, jTable_serverSocket,jTextArea_valueClientSocket, 1);
                /*try{
                    jEditorPane_descriptionServerSocket.setEditable(false);
                    String url4EditorPane="http://docs.oracle.com/javase/7/docs/api/java/net/ServerSocket.html";
                    kayaNetworkAbstractClass1.tableInfo2EditorPane(mySunucuSoketInfos, jTable_serverSocket, url4EditorPane, jEditorPane_descriptionServerSocket);
                    //jEditorPane_descriptionServerSocket.setPage(new URL("http://docs.oracle.com/"));
                }
                catch(Exception myexception)
                {
                    jEditorPane_descriptionServerSocket.setText(myexception.toString());
                }*/
                //}
            //});

    ///////////
    jScrollPane19.setViewportView(jTable_systemProperties);

    jTabbedPane2.addTab("System", jScrollPane19);

    jTable_runtime.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null}
        },
        new String [] {
            "Title 1"
        }
    ));
    /////////// Bu kodu internetten buldum.
    // "jTable" ın "currentItemChanged" gibi bir olayı yokmuş.
    // Kendimizin yazması gerekiyor.

    ListSelectionModel rowSM2 = jTable_runtime.getSelectionModel();
    rowSM2.addListSelectionListener(new ListSelectionListener() {
        public void valueChanged(ListSelectionEvent e) {
            ListSelectionModel rowSM2 = (ListSelectionModel)e.getSource();

            uiSwingMetotlar.tableInfo2TextArea(runtimeInfos, jTable_runtime, jTextArea_descriptionSystem_Runtime);

        }
    });

    ///////////
    jScrollPane20.setViewportView(jTable_runtime);

    jTabbedPane2.addTab("Runtime", jScrollPane20);

    javax.swing.GroupLayout jFrame_systemPropertiesLayout = new javax.swing.GroupLayout(jFrame_systemProperties.getContentPane());
    jFrame_systemProperties.getContentPane().setLayout(jFrame_systemPropertiesLayout);
    jFrame_systemPropertiesLayout.setHorizontalGroup(
        jFrame_systemPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jFrame_systemPropertiesLayout.createSequentialGroup()
            .addGap(25, 25, 25)
            .addGroup(jFrame_systemPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jScrollPane12)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    jFrame_systemPropertiesLayout.setVerticalGroup(
        jFrame_systemPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jFrame_systemPropertiesLayout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel19)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(20, 20, 20))
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jButton_Git.setText("Git");
    jButton_Git.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_GitActionPerformed(evt);
        }
    });

    jTextField_URL.setText("http://");

    jLabel1.setText("URL : ");

    jTextArea_Mesaj.setColumns(20);
    jTextArea_Mesaj.setEditable(false);
    jTextArea_Mesaj.setLineWrap(true);
    jTextArea_Mesaj.setRows(5);
    jScrollPane14.setViewportView(jTextArea_Mesaj);

    jTabbedPane1.addTab("Mesaj", jScrollPane14);

    jLabel14.setText(">");

    jButton_Execute.setText("Execute");
    jButton_Execute.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_ExecuteActionPerformed(evt);
        }
    });

    jLabel17.setText("Shell Command History");

    jTextArea_ShellVerbose.setColumns(20);
    jTextArea_ShellVerbose.setEditable(false);
    jTextArea_ShellVerbose.setLineWrap(true);
    jTextArea_ShellVerbose.setRows(5);
    jTextArea_ShellVerbose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jScrollPane_ShellVerbose.setViewportView(jTextArea_ShellVerbose);

    jList_shellCommandHistory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jScrollPane_shellCommandHistory.setViewportView(jList_shellCommandHistory);
    MouseListener mouseListener = new MouseAdapter() {

        public void mouseClicked(MouseEvent mouseEvent) {
            JList theList = (JList) mouseEvent.getSource();
            if (mouseEvent.getClickCount() == 2) {  // double click
                String komut = (String)theList.getSelectedValue();
                executeCommand_in_Thread(komut);
            }
        }
    };
    jList_shellCommandHistory.addMouseListener(mouseListener);

    jLabel22.setText("Verbose : ");

    jButton_clearVerbose.setText("Clear");
    jButton_clearVerbose.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_clearVerboseActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
    jPanel6.setLayout(jPanel6Layout);
    jPanel6Layout.setHorizontalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(jLabel14)
            .addGap(10, 10, 10)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addComponent(jTextField_Command)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton_Execute, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane_ShellVerbose, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel_shellVerbose_executing, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButton_clearVerbose)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addComponent(jScrollPane_shellCommandHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
            .addContainerGap())
    );
    jPanel6Layout.setVerticalGroup(
        jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel6Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_Execute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_Command)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel_shellVerbose_executing, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButton_clearVerbose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane_ShellVerbose)
                .addComponent(jScrollPane_shellCommandHistory, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
            .addContainerGap())
    );

    jScrollPane15.setViewportView(jPanel6);

    jTabbedPane1.addTab("Shell", jScrollPane15);

    jTable_URL.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Title 1", "Title 2", "Title 3"
        }
    ));
    jScrollPane1.setViewportView(jTable_URL);

    jTabbedPane1.addTab("URL Bilgisi", jScrollPane1);

    jTextArea_HTMLKaynak.setColumns(20);
    jTextArea_HTMLKaynak.setEditable(false);
    jTextArea_HTMLKaynak.setLineWrap(true);
    jTextArea_HTMLKaynak.setRows(5);
    jScrollPane2.setViewportView(jTextArea_HTMLKaynak);

    jTabbedPane1.addTab("HTML Kaynak", jScrollPane2);

    jScrollPane10.setViewportView(jEditorPane_url);

    jTabbedPane1.addTab("tab6", jScrollPane10);

    jLabel2.setText("MimeMessage.setFrom(Address)");

    jLabel3.setText("MimeMessage.setRecipients(Message.RecipientType type, String addresses) ");

    jLabel4.setText("MimeMessage.setSubject(String subject) ");

    jTextArea_setText.setColumns(20);
    jTextArea_setText.setLineWrap(true);
    jTextArea_setText.setRows(5);
    jScrollPane4.setViewportView(jTextArea_setText);

    jLabel6.setText("MimeMessage.setText(String text) ");

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Eposta Detaylar"));

    jLabel7.setText("Properties.put(\"mail.smtp.host\",");

    jLabel8.setText("Properties.put(\"mail.smtp.port\",");

    jLabel9.setText("Properties.put(\"mail.smtp.auth\",");

    jLabel10.setText("Properties.put(\"mail.smtp.starttls.enable\",");

    jLabel11.setText("Properties.put(\"mail.smtp.auth\",");

    jLabel13.setText("Properties.put(\"mail.debug\", ");

    jComboBox_smtpHost.setEditable(true);
    jComboBox_smtpHost.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "null", "localhost", "smtp.gmail.com", "smtp.mail.yahoo.com", " " }));

    jSpinner_smtpPort.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));

    jComboBox_smtpAuth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "null", "False", "True" }));

    jComboBox_smtpStartTLS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "null", "False", "True" }));

    jButton_sendEPosta.setText(" Transport.send( message )");
    jButton_sendEPosta.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_sendEPostaActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jComboBox_smtpHost, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jSpinner_smtpPort))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGap(85, 85, 85)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox_smtpAuth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox_smtpStartTLS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_sendEPosta, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );

    jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel13, jLabel7, jLabel8, jLabel9});

    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(jComboBox_smtpHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8)
                .addComponent(jSpinner_smtpPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(jComboBox_smtpAuth))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10)
                .addComponent(jComboBox_smtpStartTLS))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel13)
                .addComponent(jButton_sendEPosta))
            .addGap(17, 17, 17)
            .addComponent(jLabel11)
            .addGap(0, 317, Short.MAX_VALUE))
    );

    jLabel5.setText("Properties.put(\"mail.smtp.password\",");

    jTextArea_epostaVerbose.setColumns(20);
    jTextArea_epostaVerbose.setLineWrap(true);
    jTextArea_epostaVerbose.setRows(5);
    jScrollPane5.setViewportView(jTextArea_epostaVerbose);

    jLabel12.setText("Verbose");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                    .addComponent(jTextField_setFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPasswordField_password, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField_setRecipient)
                .addComponent(jTextField_setSubject)
                .addComponent(jScrollPane4)
                .addComponent(jScrollPane5))
            .addContainerGap(71, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jTextField_setFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5)
                .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(6, 6, 6)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(jTextField_setRecipient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(6, 6, 6)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(jTextField_setSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addContainerGap())
    );

    jScrollPane3.setViewportView(jPanel2);

    jTabbedPane1.addTab("Java Mail", jScrollPane3);

    jFileChooser1=null;
    jScrollPane6.setViewportView(jFileChooser1);

    jTabbedPane1.addTab("tab4", jScrollPane6);

    jLabel16.setText("List of Network Interfaces");

    jList_networkArayuzler.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
        public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            jList_networkArayuzlerValueChanged(evt);
        }
    });
    jScrollPane8.setViewportView(jList_networkArayuzler);

    jButton_getNetworkInterfaces.setText("<html>NetworkInterface.<br>getNetworkInterfaces()");
    jButton_getNetworkInterfaces.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_getNetworkInterfacesActionPerformed(evt);
        }
    });

    jTable_networkArayuz.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null}
        },
        new String [] {
            "Title 1"
        }
    ));
    /////////// Bu kodu internetten buldum.
    // "jTable" ın "currentItemChanged" gibi bir olayı yokmuş.
    // Kendimizin yazması gerekiyor.

    ListSelectionModel rowSM = jTable_networkArayuz.getSelectionModel();
    rowSM.addListSelectionListener(new ListSelectionListener() {
        public void valueChanged(ListSelectionEvent e) {
            ListSelectionModel rowSM = (ListSelectionModel)e.getSource();
            //int selectedIndex = rowSM.getMinSelectionIndex();
            // do something with selected index
            uiSwingMetotlar.tableInfo2TextArea(networkArayuzInfos, jTable_networkArayuz, jTextArea_descriptionNetworkArayuz);
            /*try{
                jEditorPane_descriptionServerSocket.setEditable(false);
                String url4EditorPane="http://docs.oracle.com/javase/7/docs/api/java/net/ServerSocket.html";
                kayaNetworkAbstractClass1.tableInfo2EditorPane(mySunucuSoketInfos, jTable_serverSocket, url4EditorPane, jEditorPane_descriptionServerSocket);
                //jEditorPane_descriptionServerSocket.setPage(new URL("http://docs.oracle.com/"));
            }
            catch(Exception myexception)
            {
                jEditorPane_descriptionServerSocket.setText(myexception.toString());
            }*/
        }
    });

    ///////////
    jScrollPane18.setViewportView(jTable_networkArayuz);

    jLabel18.setText("Açıklama (Description)");

    jTextArea_descriptionNetworkArayuz.setColumns(20);
    jTextArea_descriptionNetworkArayuz.setLineWrap(true);
    jTextArea_descriptionNetworkArayuz.setRows(5);
    jScrollPane9.setViewportView(jTextArea_descriptionNetworkArayuz);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton_getNetworkInterfaces, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(18, 18, 18)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jScrollPane9)
                    .addGap(14, 14, 14))
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE))
            .addGap(22, 22, 22))
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addGap(26, 26, 26)
                    .addComponent(jButton_getNetworkInterfaces, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel18)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );

    jScrollPane7.setViewportView(jPanel4);

    jTabbedPane1.addTab("Network Interfaces", jScrollPane7);

    jButton_system_runtime_PropertiesGetir.setText("System.getProperties() + Runtime.getRuntime()");
    jButton_system_runtime_PropertiesGetir.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_system_runtime_PropertiesGetirActionPerformed(evt);
        }
    });
    jScrollPane11.setViewportView(jButton_system_runtime_PropertiesGetir);

    jTabbedPane1.addTab("tab7", jScrollPane11);

    jTable_URL2.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null}
        },
        new String [] {
            "Title 1"
        }
    ));
    /////////// Bu kodu internetten buldum.
    // "jTable" ın "currentItemChanged" gibi bir olayı yokmuş.
    // Kendimizin yazması gerekiyor.

    ListSelectionModel rowSMURL2 = jTable_URL2.getSelectionModel();
    rowSMURL2.addListSelectionListener(new ListSelectionListener() {
        public void valueChanged(ListSelectionEvent e) {
            ListSelectionModel rowSMURL2 = (ListSelectionModel)e.getSource();

            uiSwingMetotlar.tableInfo2TextArea(urlInfos, jTable_URL2, jTextArea_descriptionURL_HTTP_Connection);

        }
    });

    ///////////
    jScrollPane21.setViewportView(jTable_URL2);

    jTabbedPane3.addTab("URL", jScrollPane21);

    jTable_URLConnection.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null}
        },
        new String [] {
            "Title 1"
        }
    ));
    /////////// Bu kodu internetten buldum.
    // "jTable" ın "currentItemChanged" gibi bir olayı yokmuş.
    // Kendimizin yazması gerekiyor.

    ListSelectionModel rowSMURLConnection = jTable_URLConnection.getSelectionModel();
    rowSMURLConnection.addListSelectionListener(new ListSelectionListener() {
        public void valueChanged(ListSelectionEvent e) {
            ListSelectionModel rowSMURLConnection = (ListSelectionModel)e.getSource();

            uiSwingMetotlar.tableInfo2TextArea(urlConnectionInfos, jTable_URLConnection, jTextArea_descriptionURL_HTTP_Connection);

        }
    });

    ///////////
    jScrollPane22.setViewportView(jTable_URLConnection);

    jTabbedPane3.addTab("URLConnection", jScrollPane22);

    jTable_HttpURLConnection.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null}
        },
        new String [] {
            "Title 1"
        }
    ));
    /////////// Bu kodu internetten buldum.
    // "jTable" ın "currentItemChanged" gibi bir olayı yokmuş.
    // Kendimizin yazması gerekiyor.

    ListSelectionModel rowSMHttpURLConnection = jTable_HttpURLConnection.getSelectionModel();
    rowSMHttpURLConnection.addListSelectionListener(new ListSelectionListener() {
        public void valueChanged(ListSelectionEvent e) {
            ListSelectionModel rowSMHttpURLConnection = (ListSelectionModel)e.getSource();

            uiSwingMetotlar.tableInfo2TextArea(HttpUrlConnectionInfos, jTable_HttpURLConnection, jTextArea_descriptionURL_HTTP_Connection);

        }
    });

    ///////////
    jScrollPane23.setViewportView(jTable_HttpURLConnection);

    jTabbedPane3.addTab("HttpURLConnection", jScrollPane23);

    jTextArea_descriptionURL_HTTP_Connection.setColumns(20);
    jTextArea_descriptionURL_HTTP_Connection.setLineWrap(true);
    jTextArea_descriptionURL_HTTP_Connection.setRows(5);
    jScrollPane13.setViewportView(jTextArea_descriptionURL_HTTP_Connection);

    jLabel20.setText("Açıklama (Description)");

    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
    jPanel5.setLayout(jPanel5Layout);
    jPanel5Layout.setHorizontalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE))
            .addContainerGap())
    );
    jPanel5Layout.setVerticalGroup(
        jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel5Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel20)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    jTabbedPane1.addTab("URL + HTTP Bilgiler", jPanel5);

    jComboBox_urlHistory.addItemListener(new java.awt.event.ItemListener() {
        public void itemStateChanged(java.awt.event.ItemEvent evt) {
            jComboBox_urlHistoryİtemStateChanged(evt);
        }
    });

    jButton_back.setText("<-");
    jButton_back.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_backActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextField_URL, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jComboBox_urlHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton_Git, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton_back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jTabbedPane1))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Git)
                    .addComponent(jComboBox_urlHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_back)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
            .addContainerGap())
    );

    jButton_setLookAndFeel.setText("UIManager.setLookAndFeel(\"com.sun.java.swing.plaf.");
    jButton_setLookAndFeel.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_setLookAndFeelActionPerformed(evt);
        }
    });

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "windows.WindowsLookAndFeel", "gtk.GTKLookAndFeel", "motif.MotifLookAndFeel", "mac.MacLookAndFeel" }));

    jButton_initializeAndSetVisible.setText("initializeAndSetVisible");
    jButton_initializeAndSetVisible.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_initializeAndSetVisibleActionPerformed(evt);
        }
    });

    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kayasServerSocketUI", "kayasClientSocket", "kayasUI" }));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jButton_setLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jButton_initializeAndSetVisible, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(101, 101, 101))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton_setLookAndFeel)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton_initializeAndSetVisible)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(34, 34, 34)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HTMLString2TextArea(String htmlKaynak, JTextArea mytextArea) {
        mytextArea.setText(htmlKaynak);
    }

    /*
     * I want to do other things while commmand-line process is running. I
     * wanted to let the thread run a "command-line" execution. Meanwhile I
     * would be able to do other things in my GUI.
     */
    private void executeCommand_in_Thread(String komut) {
        /*
         * http://stackoverflow.com/questions/5853167/runnable-with-a-parameter
         * http://stackoverflow.com/questions/877096/how-can-i-pass-a-parameter-to-a-java-thread
         *
         * http://stackoverflow.com/questions/9551630/getting-value-of-a-thread-variable-from-outside
         * http://stackoverflow.com/questions/9148899/returning-value-from-thread
         */
        final String parameter = komut; // the final is important

        Thread execute_Command_Thread = new Thread() {

            String output = "";
            String executing_String = "executing...";

            @Override
            public void run() {
                jLabel_shellVerbose_executing.setText(executing_String);
                try {
                    output = GenelMetotlar.executeString(parameter);
                } catch (Exception ex) {
                    Logger.getLogger(GenelMetotlar.class.getName()).log(Level.SEVERE, null, ex);
                    uiSwingMetotlar.exceptionHappened(ex, jTextArea_Mesaj);
                }
                // send output of Command to corresponding "JTextArea" object.
                jTextArea_ShellVerbose.append(output);
                // the executed command can be used later again, like in MATLAB, Terminal etc.
                uiSwingMetotlar.element2JList(parameter, jList_shellCommandHistory);
                //For "jTextArea_ShellVerbose", I want to see the most recent output, so I want the bottom view
                uiSwingMetotlar.setViewOfJTextArea2Bottom(jTextArea_ShellVerbose);

                //For "jList_shellCommandHistory", I want to see the most recent command, so I want the bottom view
                uiSwingMetotlar.setScrollPaneView_Top_or_Bottom(jScrollPane_shellCommandHistory, false);

                // execution finished
                jLabel_shellVerbose_executing.setText("");
            }
        };

        execute_Command_Thread.start();
    }

    private void jButton_GitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GitActionPerformed
        try {
            // TODO add your handling code here:
            String urlstr = jTextField_URL.getText();
            URL myurl = new URL(urlstr);

            // show the webpage in corresponding pane, but regard the following link.
            // http://stackoverflow.com/questions/4153806/jeditorpane-as-a-web-browser?rq=1
            //jEditorPane_url.setPage(myurl);   // programı yavaşlatıyor, belki kendisi için ayrı bir thread gerekli.

            // URL
            urlInfos = kayaNetworkAbstractClass1.urlBilgileri(myurl);
            uiSwingMetotlar.bilgiler2Table(urlInfos, jTable_URL);
            uiSwingMetotlar.bilgiler2Table(urlInfos, jTable_URL2);

            // URLConnection
            URLConnection urlBaglanti = myurl.openConnection();
            urlConnectionInfos = kayaNetworkAbstractClass1.urlConnectionBilgileri(urlBaglanti);
            uiSwingMetotlar.bilgiler2Table(urlConnectionInfos, jTable_URLConnection);

            //HttpURLConnection
            HttpURLConnection httpurlBaglanti = (HttpURLConnection) urlBaglanti;
            HttpUrlConnectionInfos = kayaNetworkAbstractClass1.httpURLConnectionBilgileri(httpurlBaglanti);
            uiSwingMetotlar.bilgiler2Table(HttpUrlConnectionInfos, jTable_HttpURLConnection);

            String html = kayaNetworkAbstractClass1.readURLDirectly2HTMLString(myurl);
            HTMLString2TextArea(html, jTextArea_HTMLKaynak);

            // This visited URL will be added to the top of "URL History" combobox.
            // Also keep track of visited URLs in the code, do not lose info.
            visitedURLs.add(myurl);
            
            // The URL should be inserted to the beginning of the list, because it is most recent item.
            //jComboBox_urlHistory.addItem(urlstr);     // this adds to the end.
            ((DefaultComboBoxModel) jComboBox_urlHistory.getModel()).insertElementAt(urlstr, 0);
            //jComboBox_urlHistory.setSelectedIndex(-1);      // After the visit, I want nothing to be displayed in the combobox.

        } catch (IOException ex) {
            Logger.getLogger(kayasUI.class.getName()).log(Level.SEVERE, null, ex);
            uiSwingMetotlar.exceptionHappened(ex, jTextArea_Mesaj);
        }
    }//GEN-LAST:event_jButton_GitActionPerformed

    /*
     * LOOK AND FEEL set LookAndFeel chosen from the listbox
     */
    private void jButton_setLookAndFeelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_setLookAndFeelActionPerformed
        // TODO add your handling code here:
        String LAF = jComboBox1.getSelectedItem().toString();
        LAF = "com.sun.java.swing.plaf." + LAF;
        try {
            //  look and feel değiştir.
            UIManager.setLookAndFeel(LAF);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(kayasUI.class.getName()).log(Level.SEVERE, null, ex);
            uiSwingMetotlar.exceptionHappened(ex, jTextArea_Mesaj);
        } catch (InstantiationException ex) {
            Logger.getLogger(kayasUI.class.getName()).log(Level.SEVERE, null, ex);
            uiSwingMetotlar.exceptionHappened(ex, jTextArea_Mesaj);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(kayasUI.class.getName()).log(Level.SEVERE, null, ex);
            uiSwingMetotlar.exceptionHappened(ex, jTextArea_Mesaj);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(kayasUI.class.getName()).log(Level.SEVERE, null, ex);
            uiSwingMetotlar.exceptionHappened(ex, jTextArea_Mesaj);
        }
    }//GEN-LAST:event_jButton_setLookAndFeelActionPerformed

    private void jButton_initializeAndSetVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_initializeAndSetVisibleActionPerformed
        // TODO add your handling code here:
        JFrame pencere = null;
        int indeks = jComboBox2.getSelectedIndex();
        switch (indeks) {
            case 0:
                pencere = new kayasServerSocketUI();
                break;
            case 1:
                pencere = new kayasClientSocket();
                break;
            case 2:
                pencere = new kayasUI();
                break;
            default:
                break;
        }
        pencere.setVisible(true);
    }//GEN-LAST:event_jButton_initializeAndSetVisibleActionPerformed

    private void jButton_sendEPostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sendEPostaActionPerformed
        // TODO add your handling code here:
        jTextArea_epostaVerbose.setText(null);  // verbose sıfırla.

        String from = jTextField_setFrom.getText().trim();
        String to = jTextField_setRecipient.getText().trim();
        String konu = jTextField_setSubject.getText().trim();
        String mesaj = jTextArea_setText.getText().trim();

        // detaylar
        LinkedList<String> epostaDetaylar = new LinkedList<String>();
        epostaDetaylar.add(String.valueOf(jPasswordField_password.getPassword()).trim());
        epostaDetaylar.add(jComboBox_smtpHost.getSelectedItem().toString().trim());
        epostaDetaylar.add((jSpinner_smtpPort.getValue().toString().trim()));
        epostaDetaylar.add(jComboBox_smtpAuth.getSelectedItem().toString().trim());
        epostaDetaylar.add(jComboBox_smtpStartTLS.getSelectedItem().toString().trim());

        try {
            kayaNetworkAbstractClass1.epostaGonder(from, to, konu, mesaj, epostaDetaylar);
            jTextArea_epostaVerbose.setText("Mesaj gitti.");
        } catch (AddressException ex) {
            Logger.getLogger(kayasUI.class.getName()).log(Level.SEVERE, null, ex);
            jTextArea_epostaVerbose.setText(ex.toString());
            uiSwingMetotlar.exceptionHappened(ex, jTextArea_Mesaj);
            //jTextArea_epostaVerbose.setText(ex.getMessage());
        } catch (MessagingException ex) {
            Logger.getLogger(kayasUI.class.getName()).log(Level.SEVERE, null, ex);
            jTextArea_epostaVerbose.setText(ex.toString());
            uiSwingMetotlar.exceptionHappened(ex, jTextArea_Mesaj);
        }
    }//GEN-LAST:event_jButton_sendEPostaActionPerformed

    private void jButton_getNetworkInterfacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_getNetworkInterfacesActionPerformed

        // liste ve tabloyu sıfırla.
        jList_networkArayuzler.removeAll();
        jTable_networkArayuz.removeAll();
        try {
            // TODO add your handling code here:
            Enumeration<NetworkInterface> networkArayuzEnum = NetworkInterface.getNetworkInterfaces();
            networkArayuzList = new LinkedList<NetworkInterface>();
            LinkedList<String> tmpList = new LinkedList<String>();    // JList'te gösterim için "NetworkInterface" nesnelerinin isimlerini ayrı ayrı göndersem daha iyi olacak.
            while (networkArayuzEnum.hasMoreElements()) {
                networkArayuzList.add(networkArayuzEnum.nextElement());
                tmpList.add(networkArayuzList.getLast().getDisplayName());
            }
            uiSwingMetotlar.LinkedList2JList(tmpList, jList_networkArayuzler);
        } catch (SocketException ex) {
            Logger.getLogger(kayasUI.class.getName()).log(Level.SEVERE, null, ex);
            uiSwingMetotlar.exceptionHappened(ex, jTextArea_Mesaj);
        }
    }//GEN-LAST:event_jButton_getNetworkInterfacesActionPerformed

    private void jList_networkArayuzlerValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_networkArayuzlerValueChanged
        // TODO add your handling code here:
        int indeks = jList_networkArayuzler.getSelectedIndex();
        if (indeks < 0) // nesne yenilenince indeks=-1 oluyor ve bir değişiklik olduğu için bu metot çağırılıyor, indeks=- olunca da "java.lang.IndexOutOfBoundsException" alıyorum.
        {
            return;
        }
        try {
            networkArayuzInfos = kayaNetworkAbstractClass1.networkInterfaceBilgileri(networkArayuzList.get(indeks));
            uiSwingMetotlar.bilgiler2Table(networkArayuzInfos, jTable_networkArayuz);
        } catch (SocketException ex) {
            Logger.getLogger(kayasUI.class.getName()).log(Level.SEVERE, null, ex);
            uiSwingMetotlar.exceptionHappened(ex, jTextArea_Mesaj);
        }

    }//GEN-LAST:event_jList_networkArayuzlerValueChanged

    private void jButton_system_runtime_PropertiesGetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_system_runtime_PropertiesGetirActionPerformed
        // TODO add your handling code here:
        jFrame_systemProperties.setVisible(true);
        jFrame_systemProperties.pack();

        systemPropertiesInfos = kayaNetworkAbstractClass1.systemPropertiesBilgileri();
        uiSwingMetotlar.bilgiler2Table(systemPropertiesInfos, jTable_systemProperties);

        runtimeInfos = kayaNetworkAbstractClass1.runtimeBilgileri();
        uiSwingMetotlar.bilgiler2Table(runtimeInfos, jTable_runtime);
    }//GEN-LAST:event_jButton_system_runtime_PropertiesGetirActionPerformed

    private void jButton_ExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExecuteActionPerformed
        // TODO add your handling code here:

        String komut = jTextField_Command.getText().trim();
        executeCommand_in_Thread(komut);
        /*
         * String output = ""; try { //output =
         * GenelMetotlar.executeString(komut); output =
         * GenelMetotlar.executeString_in_Thread(komut); } catch (Exception ex)
         * { Logger.getLogger(kayasUI.class.getName()).log(Level.SEVERE, null,
         * ex); uiSwingMetotlar.exceptionHappened(ex, jTextArea_Mesaj); } //
         * send output of Command to corresponding "JTextArea" object.
         * jTextArea_ShellVerbose.append(output); // For
         * "jTextArea_ShellVerbose", I want to see the most recent output, so I
         * want the bottom view
         * uiSwingMetotlar.setScrollPaneView_Top_or_Bottom(jScrollPane_ShellVerbose,
         * false); // the executed command can be used later again, like in
         * MATLAB, Terminal etc. uiSwingMetotlar.element2JList(komut,
         * jList_shellCommandHistory); // For "jList_shellCommandHistory", I
         * want to see the most recent command, so I want the bottom view
         * uiSwingMetotlar.setScrollPaneView_Top_or_Bottom(jScrollPane_shellCommandHistory,
         * false);
         *
         */
    }//GEN-LAST:event_jButton_ExecuteActionPerformed

    private void jButton_clearVerboseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_clearVerboseActionPerformed
        // TODO add your handling code here:
        jTextArea_ShellVerbose.setText(null);
    }//GEN-LAST:event_jButton_clearVerboseActionPerformed

    private void jComboBox_urlHistoryİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_urlHistoryİtemStateChanged
        // TODO add your handling code here:
        String selectedURL=(String) jComboBox_urlHistory.getSelectedItem();
        jTextField_URL.setText(selectedURL);
    }//GEN-LAST:event_jComboBox_urlHistoryİtemStateChanged

    /*
     * visit second most recent visited URL, ie. previous URL
     */
    private void jButton_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_backActionPerformed
        // TODO add your handling code here:
        int previousURLindex=1;
        String lastURL=(String) jComboBox_urlHistory.getModel().getElementAt(previousURLindex);
        jTextField_URL.setText(lastURL);
        jButton_GitActionPerformed(evt);
    }//GEN-LAST:event_jButton_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException, IOException {

        // set "LookAndFeel" to the default one
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        //
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new kayasUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Execute;
    private javax.swing.JButton jButton_Git;
    private javax.swing.JButton jButton_back;
    private javax.swing.JButton jButton_clearVerbose;
    private javax.swing.JButton jButton_getNetworkInterfaces;
    private javax.swing.JButton jButton_initializeAndSetVisible;
    private javax.swing.JButton jButton_sendEPosta;
    private javax.swing.JButton jButton_setLookAndFeel;
    private javax.swing.JButton jButton_system_runtime_PropertiesGetir;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox_smtpAuth;
    private javax.swing.JComboBox jComboBox_smtpHost;
    private javax.swing.JComboBox jComboBox_smtpStartTLS;
    private javax.swing.JComboBox jComboBox_urlHistory;
    private javax.swing.JEditorPane jEditorPane_url;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame_systemProperties;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_shellVerbose_executing;
    private javax.swing.JList jList_networkArayuzler;
    private javax.swing.JList jList_shellCommandHistory;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JScrollPane jScrollPane_ShellVerbose;
    private javax.swing.JScrollPane jScrollPane_shellCommandHistory;
    private javax.swing.JSpinner jSpinner_smtpPort;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTable_HttpURLConnection;
    private javax.swing.JTable jTable_URL;
    private javax.swing.JTable jTable_URL2;
    private javax.swing.JTable jTable_URLConnection;
    private javax.swing.JTable jTable_networkArayuz;
    private javax.swing.JTable jTable_runtime;
    private javax.swing.JTable jTable_systemProperties;
    private javax.swing.JTextArea jTextArea_HTMLKaynak;
    private javax.swing.JTextArea jTextArea_Mesaj;
    private javax.swing.JTextArea jTextArea_ShellVerbose;
    private javax.swing.JTextArea jTextArea_descriptionNetworkArayuz;
    private javax.swing.JTextArea jTextArea_descriptionSystem_Runtime;
    private javax.swing.JTextArea jTextArea_descriptionURL_HTTP_Connection;
    private javax.swing.JTextArea jTextArea_epostaVerbose;
    private javax.swing.JTextArea jTextArea_setText;
    private javax.swing.JTextField jTextField_Command;
    private javax.swing.JTextField jTextField_URL;
    private javax.swing.JTextField jTextField_setFrom;
    private javax.swing.JTextField jTextField_setRecipient;
    private javax.swing.JTextField jTextField_setSubject;
    // End of variables declaration//GEN-END:variables
}
