/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * kayasUI.java
 *
 * Created on Feb 24, 2012, 9:13:09 PM
 */

package kaya.kayasUIpaket;
import javax.swing.UnsupportedLookAndFeelException;
import kaya.kayaClassPaket.*;
//import java.io.BufferedReader;
//import java.io.IOException;
//import java.io.InputStreamReader;
import java.io.*;   /////////
import java.net.*;///////
import java.nio.file.FileVisitOption;
import java.nio.file.Files;
import java.util.EnumSet;
import java.util.Enumeration;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.mail.MessagingException;
import javax.mail.internet.AddressException;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.filechooser.FileSystemView;
import kaya.kayasServerUIpaket.kayasClientSocket;
import kaya.kayasServerUIpaket.kayasServerSocketUI;

/**
 *
 * @author kaya
 */
public class kayasUI extends javax.swing.JFrame {

    // global degiskenler
    LinkedList<NetworkInterface> networkArayuzList;
    LinkedList<LinkedList<String>> networkArayuzInfos;
    LinkedList<LinkedList<String>> systemPropertiesInfos;
    
    /** Creates new form kayasUI */
    public kayasUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame_systemProperties = new javax.swing.JFrame();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTable_systemProperties = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButton_Git = new javax.swing.JButton();
        jTextField_URL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_URL = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea_HTMLKaynak = new javax.swing.JTextArea();
        jScrollPane10 = new javax.swing.JScrollPane();
        jEditorPane_url = new javax.swing.JEditorPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_setFrom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_setRecipient = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_setSubject = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_setText = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jComboBox_smtpHost = new javax.swing.JComboBox();
        jSpinner_smtpPort = new javax.swing.JSpinner();
        jComboBox_smtpAuth = new javax.swing.JComboBox();
        jComboBox_smtpStartTLS = new javax.swing.JComboBox();
        jButton_sendEPosta = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField_password = new javax.swing.JPasswordField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea_epostaVerbose = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane7 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jList_networkArayuzler = new javax.swing.JList();
        jButton_getNetworkInterfaces = new javax.swing.JButton();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTable_networkArayuz = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea_descriptionNetworkArayuz = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        jButton_systemPropertiesGetir = new javax.swing.JButton();
        jButton_setLookAndFeel = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton_initializeAndSetVisible = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();

        jPanel10.setAutoscrolls(true);

        jTable_systemProperties.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        /////////// Bu kodu internetten buldum.
        // "jTable" ın "currentItemChanged" gibi bir olayı yokmuş.
        // Kendimizin yazması gerekiyor.

        //    ListSelectionModel rowSM2 = jTable_serverSocket.getSelectionModel();
        //rowSM2.addListSelectionListener(new ListSelectionListener() {
            //public void valueChanged(ListSelectionEvent e) {
                //ListSelectionModel rowSM2 = (ListSelectionModel)e.getSource();
                //int selectedIndex = rowSM.getMinSelectionIndex();
                // do something with selected index
                //kayaNetworkAbstractClass1.tableInfo2TextArea(mySunucuSoketInfos, jTable_serverSocket, jTextArea_descriptionServerSocket);
                //kayaNetworkAbstractClass1.tableInfo2TextArea(mySunucuSoketInfos, jTable_serverSocket,jTextArea_valueClientSocket, 1);
                /*try{
                    jEditorPane_descriptionServerSocket.setEditable(false);
                    String url4EditorPane="http://docs.oracle.com/javase/7/docs/api/java/net/ServerSocket.html";
                    kayaNetworkAbstractClass1.tableInfo2EditorPane(mySunucuSoketInfos, jTable_serverSocket, url4EditorPane, jEditorPane_descriptionServerSocket);
                    //jEditorPane_descriptionServerSocket.setPage(new URL("http://docs.oracle.com/"));
                }
                catch(Exception myexception)
                {
                    jEditorPane_descriptionServerSocket.setText(myexception.toString());
                }*/
                //}
            //});

    ///////////
    jScrollPane19.setViewportView(jTable_systemProperties);

    javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
    jPanel10.setLayout(jPanel10Layout);
    jPanel10Layout.setHorizontalGroup(
        jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel10Layout.createSequentialGroup()
            .addGap(5, 5, 5)
            .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    jPanel10Layout.setVerticalGroup(
        jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel10Layout.createSequentialGroup()
            .addGap(5, 5, 5)
            .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    javax.swing.GroupLayout jFrame_systemPropertiesLayout = new javax.swing.GroupLayout(jFrame_systemProperties.getContentPane());
    jFrame_systemProperties.getContentPane().setLayout(jFrame_systemPropertiesLayout);
    jFrame_systemPropertiesLayout.setHorizontalGroup(
        jFrame_systemPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 486, Short.MAX_VALUE)
        .addGroup(jFrame_systemPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_systemPropertiesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(17, Short.MAX_VALUE)))
    );
    jFrame_systemPropertiesLayout.setVerticalGroup(
        jFrame_systemPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 471, Short.MAX_VALUE)
        .addGroup(jFrame_systemPropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame_systemPropertiesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(26, Short.MAX_VALUE)))
    );

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jButton_Git.setText("Git");
    jButton_Git.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_GitActionPerformed(evt);
        }
    });

    jTextField_URL.setText("http://");
    jTextField_URL.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jTextField_URLActionPerformed(evt);
        }
    });

    jLabel1.setText("URL : ");

    jTable_URL.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Title 1", "Title 2", "Title 3"
        }
    ));
    jScrollPane1.setViewportView(jTable_URL);

    jTabbedPane1.addTab("URL Bilgisi", jScrollPane1);

    jTextArea_HTMLKaynak.setColumns(20);
    jTextArea_HTMLKaynak.setEditable(false);
    jTextArea_HTMLKaynak.setLineWrap(true);
    jTextArea_HTMLKaynak.setRows(5);
    jScrollPane2.setViewportView(jTextArea_HTMLKaynak);

    jTabbedPane1.addTab("HTML Kaynak", jScrollPane2);

    jScrollPane10.setViewportView(jEditorPane_url);

    jTabbedPane1.addTab("tab6", jScrollPane10);

    jLabel2.setText("MimeMessage.setFrom(Address)");

    jLabel3.setText("MimeMessage.setRecipients(Message.RecipientType type, String addresses) ");

    jLabel4.setText("MimeMessage.setSubject(String subject) ");

    jTextArea_setText.setColumns(20);
    jTextArea_setText.setLineWrap(true);
    jTextArea_setText.setRows(5);
    jScrollPane4.setViewportView(jTextArea_setText);

    jLabel6.setText("MimeMessage.setText(String text) ");

    jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Eposta Detaylar"));

    jLabel7.setText("Properties.put(\"mail.smtp.host\",");

    jLabel8.setText("Properties.put(\"mail.smtp.port\",");

    jLabel9.setText("Properties.put(\"mail.smtp.auth\",");

    jLabel10.setText("Properties.put(\"mail.smtp.starttls.enable\",");

    jLabel11.setText("Properties.put(\"mail.smtp.auth\",");

    jLabel13.setText("Properties.put(\"mail.debug\", ");

    jComboBox_smtpHost.setEditable(true);
    jComboBox_smtpHost.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "null", "localhost", "smtp.gmail.com", "smtp.mail.yahoo.com", " " }));

    jSpinner_smtpPort.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(-1), Integer.valueOf(-1), null, Integer.valueOf(1)));

    jComboBox_smtpAuth.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "null", "False", "True" }));

    jComboBox_smtpStartTLS.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "null", "False", "True" }));

    jButton_sendEPosta.setText(" Transport.send( message )");
    jButton_sendEPosta.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_sendEPostaActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(10, 10, 10)
                    .addComponent(jComboBox_smtpHost, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jSpinner_smtpPort))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGap(85, 85, 85)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jComboBox_smtpAuth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox_smtpStartTLS, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_sendEPosta, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap())
    );

    jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel13, jLabel7, jLabel8, jLabel9});

    jPanel3Layout.setVerticalGroup(
        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(jComboBox_smtpHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel8)
                .addComponent(jSpinner_smtpPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel9)
                .addComponent(jComboBox_smtpAuth))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel10)
                .addComponent(jComboBox_smtpStartTLS))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel13)
                .addComponent(jButton_sendEPosta))
            .addGap(17, 17, 17)
            .addComponent(jLabel11)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    jLabel5.setText("Properties.put(\"mail.smtp.password\",");

    jTextArea_epostaVerbose.setColumns(20);
    jTextArea_epostaVerbose.setLineWrap(true);
    jTextArea_epostaVerbose.setRows(5);
    jScrollPane5.setViewportView(jTextArea_epostaVerbose);

    jLabel12.setText("Verbose");

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField_setFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jPasswordField_password, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jTextField_setRecipient)
                .addComponent(jTextField_setSubject)
                .addComponent(jScrollPane4)
                .addComponent(jScrollPane5))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel2Layout.setVerticalGroup(
        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel2Layout.createSequentialGroup()
            .addGap(14, 14, 14)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jTextField_setFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5)
                .addComponent(jPasswordField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(6, 6, 6)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3)
                .addComponent(jTextField_setRecipient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(6, 6, 6)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(jTextField_setSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jLabel6)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );

    jScrollPane3.setViewportView(jPanel2);

    jTabbedPane1.addTab("Java Mail", jScrollPane3);

    jFileChooser1=null;
    jScrollPane6.setViewportView(jFileChooser1);

    jTabbedPane1.addTab("tab4", jScrollPane6);

    jLabel16.setText("List of Network Interfaces");

    jList_networkArayuzler.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
        public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
            jList_networkArayuzlerValueChanged(evt);
        }
    });
    jScrollPane8.setViewportView(jList_networkArayuzler);

    jButton_getNetworkInterfaces.setText("<html>NetworkInterface.<br>getNetworkInterfaces()");
    jButton_getNetworkInterfaces.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_getNetworkInterfacesActionPerformed(evt);
        }
    });

    jTable_networkArayuz.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {
            {null}
        },
        new String [] {
            "Title 1"
        }
    ));
    /////////// Bu kodu internetten buldum.
    // "jTable" ın "currentItemChanged" gibi bir olayı yokmuş.
    // Kendimizin yazması gerekiyor.

    ListSelectionModel rowSM = jTable_networkArayuz.getSelectionModel();
    rowSM.addListSelectionListener(new ListSelectionListener() {
        public void valueChanged(ListSelectionEvent e) {
            ListSelectionModel rowSM = (ListSelectionModel)e.getSource();
            //int selectedIndex = rowSM.getMinSelectionIndex();
            // do something with selected index
            uiSwingMetotlar.tableInfo2TextArea(networkArayuzInfos, jTable_networkArayuz, jTextArea_descriptionNetworkArayuz);
            /*try{
                jEditorPane_descriptionServerSocket.setEditable(false);
                String url4EditorPane="http://docs.oracle.com/javase/7/docs/api/java/net/ServerSocket.html";
                kayaNetworkAbstractClass1.tableInfo2EditorPane(mySunucuSoketInfos, jTable_serverSocket, url4EditorPane, jEditorPane_descriptionServerSocket);
                //jEditorPane_descriptionServerSocket.setPage(new URL("http://docs.oracle.com/"));
            }
            catch(Exception myexception)
            {
                jEditorPane_descriptionServerSocket.setText(myexception.toString());
            }*/
        }
    });

    ///////////
    jScrollPane18.setViewportView(jTable_networkArayuz);

    jLabel18.setText("Açıklama (Description)");

    jTextArea_descriptionNetworkArayuz.setColumns(20);
    jTextArea_descriptionNetworkArayuz.setLineWrap(true);
    jTextArea_descriptionNetworkArayuz.setRows(5);
    jScrollPane9.setViewportView(jTextArea_descriptionNetworkArayuz);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(12, 12, 12)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE))
                .addComponent(jButton_getNetworkInterfaces, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)
                        .addComponent(jScrollPane9))))
            .addContainerGap())
    );
    jPanel4Layout.setVerticalGroup(
        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel4Layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addComponent(jScrollPane18, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jLabel18)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addComponent(jButton_getNetworkInterfaces))
            .addContainerGap())
    );

    jScrollPane7.setViewportView(jPanel4);

    jTabbedPane1.addTab("Network Interfaces", jScrollPane7);

    jButton_systemPropertiesGetir.setText("System.getProperties()");
    jButton_systemPropertiesGetir.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_systemPropertiesGetirActionPerformed(evt);
        }
    });
    jScrollPane11.setViewportView(jButton_systemPropertiesGetir);

    jTabbedPane1.addTab("tab7", jScrollPane11);

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jTextField_URL)
                    .addGap(18, 18, 18)
                    .addComponent(jButton_Git, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 777, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(jLabel1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_URL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Git)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    jButton_setLookAndFeel.setText("UIManager.setLookAndFeel(\"com.sun.java.swing.plaf.");
    jButton_setLookAndFeel.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_setLookAndFeelActionPerformed(evt);
        }
    });

    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "windows.WindowsLookAndFeel", "gtk.GTKLookAndFeel", "motif.MotifLookAndFeel", "mac.MacLookAndFeel" }));

    jButton_initializeAndSetVisible.setText("initializeAndSetVisible");
    jButton_initializeAndSetVisible.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton_initializeAndSetVisibleActionPerformed(evt);
        }
    });

    jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kayasServerSocketUI", "kayasClientSocket", "kayasUI" }));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jButton_setLookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jButton_initializeAndSetVisible, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(101, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton_setLookAndFeel)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jButton_initializeAndSetVisible)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents


    private void HTMLString2TextArea(String htmlKaynak, JTextArea mytextArea)
    {
        mytextArea.setText(htmlKaynak);
    }

    private void jTextField_URLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_URLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_URLActionPerformed

    private void jButton_GitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GitActionPerformed
        try {
            // TODO add your handling code here:
            String urlstr = jTextField_URL.getText();
            URL myurl = new URL(urlstr);
            
            // show the webpage in corresponding pane, but regard the following link.
            // http://stackoverflow.com/questions/4153806/jeditorpane-as-a-web-browser?rq=1
            //jEditorPane_url.setPage(myurl);   // programı yavaşlatıyor, belki kendisi için ayrı bir thread gerekli.
          
            LinkedList<LinkedList<String>> urlInfos = kayaNetworkAbstractClass1.urlBilgileri(myurl);
            uiSwingMetotlar.bilgiler2Table(urlInfos, jTable_URL);
            String html=kayaNetworkAbstractClass1.readURLDirectly2HTMLString(myurl);
            HTMLString2TextArea(html, jTextArea_HTMLKaynak);
        } catch (IOException ex) {
            Logger.getLogger(kayasUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_GitActionPerformed

    /*
     * LOOK AND FEEL
     * set LookAndFeel chosen from the listbox
     */
    private void jButton_setLookAndFeelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_setLookAndFeelActionPerformed
        // TODO add your handling code here:
        String LAF=jComboBox1.getSelectedItem().toString();
        LAF="com.sun.java.swing.plaf."+LAF;
        try {
             //  look and feel değiştir.
            UIManager.setLookAndFeel(LAF);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(kayasUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(kayasUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(kayasUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(kayasUI.class.getName()).log(Level.SEVERE, null, ex);
        }             
    }//GEN-LAST:event_jButton_setLookAndFeelActionPerformed
    
    private void jButton_initializeAndSetVisibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_initializeAndSetVisibleActionPerformed
        // TODO add your handling code here:
        JFrame pencere = null;
        int indeks=jComboBox2.getSelectedIndex();
        switch (indeks)
        {
            case 0:
                pencere=new kayasServerSocketUI();
                break;
            case 1:
                pencere=new kayasClientSocket();
                break;
            case 2:
                pencere=new kayasUI();
                break;
            default:
                break;
        }
        pencere.setVisible(true);
    }//GEN-LAST:event_jButton_initializeAndSetVisibleActionPerformed

    private void jButton_sendEPostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_sendEPostaActionPerformed
        // TODO add your handling code here:
        jTextArea_epostaVerbose.setText(null);  // verbose sıfırla.
        
        String from=jTextField_setFrom.getText().trim();
        String to=jTextField_setRecipient.getText().trim();
        String konu=jTextField_setSubject.getText().trim();
        String mesaj=jTextArea_setText.getText().trim();
        
        // detaylar
        LinkedList<String> epostaDetaylar=new LinkedList<String>();
        epostaDetaylar.add(String.valueOf(jPasswordField_password.getPassword()).trim());
        epostaDetaylar.add(jComboBox_smtpHost.getSelectedItem().toString().trim());
        epostaDetaylar.add((jSpinner_smtpPort.getValue().toString().trim()));
        epostaDetaylar.add(jComboBox_smtpAuth.getSelectedItem().toString().trim());
        epostaDetaylar.add(jComboBox_smtpStartTLS.getSelectedItem().toString().trim());
        
        try {
            kayaNetworkAbstractClass1.epostaGonder(from, to, konu, mesaj, epostaDetaylar);
            jTextArea_epostaVerbose.setText("Mesaj gitti.");
        } catch (AddressException ex) {
            Logger.getLogger(kayasUI.class.getName()).log(Level.SEVERE, null, ex);
            jTextArea_epostaVerbose.setText(ex.toString());
            //jTextArea_epostaVerbose.setText(ex.getMessage());
        } catch (MessagingException ex) {
            Logger.getLogger(kayasUI.class.getName()).log(Level.SEVERE, null, ex);
            jTextArea_epostaVerbose.setText(ex.toString());
        }
    }//GEN-LAST:event_jButton_sendEPostaActionPerformed

    private void jButton_getNetworkInterfacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_getNetworkInterfacesActionPerformed

        // liste ve tabloyu sıfırla.
        jList_networkArayuzler.removeAll();
        jTable_networkArayuz.removeAll();
        try {
            // TODO add your handling code here:
            Enumeration<NetworkInterface>   networkArayuzEnum=NetworkInterface.getNetworkInterfaces();
            networkArayuzList=new LinkedList<NetworkInterface>();
            LinkedList<String> tmpList=new LinkedList<String>();    // JList'te gösterim için "NetworkInterface" nesnelerinin isimlerini ayrı ayrı göndersem daha iyi olacak.
            while(networkArayuzEnum.hasMoreElements())
            {
                networkArayuzList.add(networkArayuzEnum.nextElement());
                tmpList.add(networkArayuzList.getLast().getDisplayName());
            }
            uiSwingMetotlar.LinkedList2JList(tmpList, jList_networkArayuzler);
        } catch (SocketException ex) {
            Logger.getLogger(kayasUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton_getNetworkInterfacesActionPerformed

    private void jList_networkArayuzlerValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList_networkArayuzlerValueChanged
        // TODO add your handling code here:
        int indeks=jList_networkArayuzler.getSelectedIndex();
        if(indeks<0)    // nesne yenilenince indeks=-1 oluyor ve bir değişiklik olduğu için bu metot çağırılıyor, indeks=- olunca da "java.lang.IndexOutOfBoundsException" alıyorum.
        {    return; }
        try {
            networkArayuzInfos=kayaNetworkAbstractClass1.networkInterfaceBilgileri(networkArayuzList.get(indeks));
            uiSwingMetotlar.bilgiler2Table(networkArayuzInfos, jTable_networkArayuz);
        } catch (SocketException ex) {
            Logger.getLogger(kayasUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jList_networkArayuzlerValueChanged

    private void jButton_systemPropertiesGetirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_systemPropertiesGetirActionPerformed
        // TODO add your handling code here:
        jFrame_systemProperties.setVisible(true);
        jFrame_systemProperties.pack();
        
        systemPropertiesInfos=kayaNetworkAbstractClass1.systemPropertiesBilgileri();
        uiSwingMetotlar.bilgiler2Table(systemPropertiesInfos, jTable_systemProperties);
    }//GEN-LAST:event_jButton_systemPropertiesGetirActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) throws ClassNotFoundException, InstantiationException, IllegalAccessException, UnsupportedLookAndFeelException, IOException {

        // set "LookAndFeel" to the default one
        UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
         //
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kayasUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Git;
    private javax.swing.JButton jButton_getNetworkInterfaces;
    private javax.swing.JButton jButton_initializeAndSetVisible;
    private javax.swing.JButton jButton_sendEPosta;
    private javax.swing.JButton jButton_setLookAndFeel;
    private javax.swing.JButton jButton_systemPropertiesGetir;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox_smtpAuth;
    private javax.swing.JComboBox jComboBox_smtpHost;
    private javax.swing.JComboBox jComboBox_smtpStartTLS;
    private javax.swing.JEditorPane jEditorPane_url;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame_systemProperties;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList_networkArayuzler;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPasswordField jPasswordField_password;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSpinner jSpinner_smtpPort;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable_URL;
    private javax.swing.JTable jTable_networkArayuz;
    private javax.swing.JTable jTable_systemProperties;
    private javax.swing.JTextArea jTextArea_HTMLKaynak;
    private javax.swing.JTextArea jTextArea_descriptionNetworkArayuz;
    private javax.swing.JTextArea jTextArea_epostaVerbose;
    private javax.swing.JTextArea jTextArea_setText;
    private javax.swing.JTextField jTextField_URL;
    private javax.swing.JTextField jTextField_setFrom;
    private javax.swing.JTextField jTextField_setRecipient;
    private javax.swing.JTextField jTextField_setSubject;
    // End of variables declaration//GEN-END:variables

}
